# Target: xcku115-flvb1760-1-c
#
# This is a template. Package pins and I/O standards are intentionally not
# selected because they depend on the PCB. Replace the commented examples
# before implementation.

# 80 MHz forwarded-clock source and VAR_LOAD control clock.
create_clock -name clk80_in -period 12.500 \
    [get_ports clk80_in]

# 300 MHz IDELAYCTRL calibration reference.
create_clock -name refclk300_in -period 3.333 \
    [get_ports refclk300_in]

# clk80_in and refclk300_in do not require a defined phase relationship.
set_clock_groups -asynchronous \
    -group [get_clocks clk80_in] \
    -group [get_clocks refclk300_in]

# ---------------------------------------------------------------------------
# Board-specific package-pin examples -- uncomment and replace as required.
# Clock inputs must use suitable clock-capable pins for the chosen bank/board.
# ---------------------------------------------------------------------------
# set_property PACKAGE_PIN <CLK80_PIN>     [get_ports clk80_in]
# set_property IOSTANDARD  <CLK80_IOSTD>   [get_ports clk80_in]
# set_property PACKAGE_PIN <REFCLK300_PIN> [get_ports refclk300_in]
# set_property IOSTANDARD  <REFCLK_IOSTD>  [get_ports refclk300_in]

# DDR_CLK must use a true differential P/N pair. BA17/BB17 is one candidate
# pair on xcku115-flvb1760, but it must first be checked against the board
# schematic and the cascade placement generated by Vivado.
#
# set_property PACKAGE_PIN BA17 [get_ports ddr_clk_p]
# set_property PACKAGE_PIN BB17 [get_ports ddr_clk_n]
# set_property IOSTANDARD <DIFF_IOSTANDARD> \
#     [get_ports {ddr_clk_p ddr_clk_n}]

# rst and sel can be driven by internal registers instead of external pins.
# If they are external, add PACKAGE_PIN/IOSTANDARD constraints here.

# Output timing must be completed for the actual receiver:
#   set_output_delay -clock <forwarded_clock> -max <receiver_setup_plus_board>
#   set_output_delay -clock <forwarded_clock> -min <-receiver_hold_plus_board>
#
# Do not copy placeholder values into sign-off constraints. The dynamic
# delay-chain setting and fixed cascade insertion delay must be included in
# the final board/interface timing analysis.
